In [1]:
import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
# Return maximum element
np.max(matrix)


9

In [3]:
import numpy as np
# Create matrix
matrix = np.array([[10, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
# Return maximum element
np.min(matrix)

2

In [4]:
import numpy as np
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [40]:
import numpy as np
x = np.ones((3, 3))
x[1:-1,1:-1] = 0
x = np.pad(x, pad_width=1, mode='constant', constant_values=2)
print(x)

[[2. 2. 2. 2. 2.]
 [2. 1. 1. 1. 2.]
 [2. 1. 0. 1. 2.]
 [2. 1. 1. 1. 2.]
 [2. 2. 2. 2. 2.]]


In [45]:
# Python3 program for printing
# the rectangular pattern
 
# Function to print the pattern
def printPattern(n):
 
    arraySize = n * 2 - 1;
    result = [[0 for x in range(arraySize)]
                 for y in range(arraySize)];
         
    # Fill the values
    for i in range(arraySize):
        for j in range(arraySize):
            if(abs(i - (arraySize // 2)) >
               abs(j - (arraySize // 2))):
                result[i][j] = abs(i - (arraySize // 2)) ;
            else:
                result[i][j] = abs(j - (arraySize // 2)) ;
             
    # Print the array
    for i in range(arraySize):
        for j in range(arraySize):
            print(result[i][j], end = " ");
        print("");
 
# Driver Code
n = 3;
 
printPattern(n);


2 2 2 2 2 
2 1 1 1 2 
2 1 0 1 2 
2 1 1 1 2 
2 2 2 2 2 
